spring:
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/${env.DB_NAME:igym_db}
    username: ${env.DB_USERNAME}
    password: ${env.DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${env.JPA_DDL_AUTO:update}
    show-sql: ${env.SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${env.FORMAT_SQL:true}
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: ${env.MAX_FILE_SIZE:10MB}
      max-request-size: ${env.MAX_REQUEST_SIZE:10MB}
  mail:
    host: ${env.MAIL_HOST:smtp.gmail.com}
    port: ${env.MAIL_PORT:587}
    username: ${env.MAIL_USERNAME}
    password: ${env.MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${env.SERVER_PORT:8080}
  error:
    include-message: always

jwt:
  secret: ${env.JWT_SECRET}
  expiration: ${env.JWT_EXPIRATION:86400000}

app:
  cors:
    allowed-origins: ${env.CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:4201}
