spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/igym_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-specific-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  error:
    include-message: always

jwt:
  secret: your_jwt_secret_key_here_make_it_long_and_secure_in_production
  expiration: 86400000 # 24 hours in milliseconds

app:
  cors:
    allowed-origins: http://localhost:4200,http://localhost:4201
